### ISSUE TITLE
dont work in Angular 6

### ISSUE THREAD

**Issue by jackillman** [lsharir/angular-d3-graph-example#3]

**Comment by lsharir** [comment]
Hey Jack, can you provide additional details on what doesn't work? and the exact version used?

**Comment by elm-suf** [comment]
@lsharir @jackillman
I have the same same problem:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.9.0
3 info using node@v11.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-d3-graph-example@0.0.1~prestart: angular-d3-graph-example@0.0.1
6 info lifecycle angular-d3-graph-example@0.0.1~start: angular-d3-graph-example@0.0.1
7 verbose lifecycle angular-d3-graph-example@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle angular-d3-graph-example@0.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/elm-suf/Projects/Cloned/angular-d3-graph-example/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle angular-d3-graph-example@0.0.1~start: CWD: /home/elm-suf/Projects/Cloned/angular-d3-graph-example
10 silly lifecycle angular-d3-graph-example@0.0.1~start: Args: [ '-c', 'ng serve' ]
11 silly lifecycle angular-d3-graph-example@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle angular-d3-graph-example@0.0.1~start: Failed to exec start script
13 verbose stack Error: angular-d3-graph-example@0.0.1 start: `ng serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:1001:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid angular-d3-graph-example@0.0.1
15 verbose cwd /home/elm-suf/Projects/Cloned/angular-d3-graph-example
16 verbose Linux 4.19.32-1-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v11.13.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error angular-d3-graph-example@0.0.1 start: `ng serve`
22 error Exit status 1
23 error Failed at the angular-d3-graph-example@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
